baseURL: "ucsal.github.io"
theme: "up-business-theme"
languageCode: "pt-br"

title: "UCSal Hub"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "UCSal Hub"
  description: "Construindo o Amanhã: UCSal Hub - Pesquisa, Desenvolvimento e Inovação."
  images: 
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    #dribbble: "#"
    instagram: "https://www.instagram.com/ucsal_oficial/"
    #facebook: "#"
    #twitter: "#"

  location:
    - "Av. Prof. Pinto de Aguiar, 2589 Pituaçu, Salvador - BA, 41740-090"    

  contact:
    - "osvaldo.melo@ucsal.br"
    - ""

  copyright: "© 2022 Up Business All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    #- name: "Como Funciona"
    #  url: "/#"
    #  weight: 2

    #- name: "Nosso Time"
    #  url: "/#"
    #  weight: 3

    #- name: "Projetos"
    #  url: "/#"
    #  weight: 4

    # - name: "Noticias"
    #   url: "/blog"
    #   weight: 5

  buttons:
    - name: "Aditamento do edital"
      url: "https://drive.google.com/file/d/1_8knqRzxjO9yxe3OKy6OtQ337wuHnFqY/view?usp=sharing"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    #- name: "Como Funciona"
    #  url: "/#"
    #  weight: 2

    #- name: "Nosso Time"
    #  url: "/#"
    #  weight: 3

    #- name: "Projetos"
    #  url: "/#"
    #  weight: 4

    #- name: "Blog"
    #  url: "/blog"
    #  weight: 5

taxonomies:
  series: "series"
  tags: "tags"
